# -*- coding: utf-8 -*-
"""Joana Naiara Atividade aula 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IX2QKQINs2j51s23dCqNdi_7B2k5CYY_
"""

import threading
import time

saldo =1000
lock= threading.Lock()

def thread_a():
    global saldo
    with lock:
        leitura = saldo
        time.sleep(1)
        leitura += 500
        saldo = leitura
        print("Thread A escreveu:{saldo}",)

def thread_b():
    global saldo
    with lock:
        leitura = saldo
        time.sleep(1)
        leitura -= 200
        saldo = leitura
        print(f"Thread B escreveu: {saldo}")

t1 = threading.Thread(target=thread_a)
t2 = threading.Thread(target=thread_b)

t1.start()
t2.start()

t1.join()
t2.join()

print(f"Saldo final: {saldo}")

t1.join()
t2.join()

print(f"Saldo final: {saldo}")