# -*- coding: utf-8 -*-
"""Exercicio_01_PedrofelipeSantiagoNeto.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBXnWMUhz3Nu7j5G6Fz9cck3jd5gWvri
"""

soma_idades = 0
maior_idade = float('-inf') # começa com o menor valor possivel
menor_idade = float('inf') # começa com o maior valor possivel
qtd_maiores_18 = 0
total_de_pessoas = 5

print (f"--- Leitura de {total_de_pessoas} idades ---\n")

# Estrutura para leitura da idade das 5 pessoas

for i in range(total_de_pessoas):
    while True: # Loop de validação
        try:
            idade = int(input(f"Digite a idade da pessoa {i + 1}:  "))
            if idade > 0 :
                break # Sai do Loop se a idade for válida.
            else:
                print("A idade deve ser maior que 0! Por favor Digite uma idade Válida novamente. ")
        except ValueError:
            print("Por favor, digite um número inteiro.")

    # Atualizando as estatisticas DENTRO do loop
    soma_idades += idade

    if idade > maior_idade:
        maior_idade = idade

    if idade < menor_idade:
        menor_idade = idade

    if idade >= 18:
        qtd_maiores_18 += 1

# Calculos da idade média
media_idades = soma_idades / total_de_pessoas

#Exibição dos resultados
print("n--- Resultados---")
print(f"Maior idade encontrada: {maior_idade}")
print(f"Menor idade encontrada {menor_idade}")
print(f"Média das idades: {media_idades:1f}")
print(f"Quantidade de Pessoas maiores de 18 anos: {qtd_maiores_18}")